#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace GSGameplayTags
{
	PROJECTF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Skill1);
	PROJECTF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Skill2);
	PROJECTF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_KineticRope);
	PROJECTF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	PROJECTF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Cooked);
	PROJECTF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Burned);
	PROJECTF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Cooled);
	PROJECTF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Filled);
	PROJECTF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Aiming);
	PROJECTF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Grab);
	PROJECTF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Launch);
	PROJECTF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_HoldingItem);
}
