name: Sincronizar Main a Repositorio Publico

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Sincronizar con el repositorio publico
        env:
          PUBLIC_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
          PUBLIC_REPO: "TheLastBonny/Good-Service-PlaceHolder-Public"
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "action@github.com"
          
          git remote add public "https://${PUBLIC_TOKEN}@github.com/${PUBLIC_REPO}.git"
          git push public main --force
